#!/bin/bash

#### BSPWM CONFIGURATION FILE ####

_Main() {

    source ~/.config/bspwm/_WindowRules

    #### MONITORS & DESKTOP SETTINGS ####
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10

    # bspc desktop ^2 -l monocle

    # External scripts & settings
    _Check launch_polybar && launch_polybar &
    _Check sxhkd-start && sxhkd-start &
    _Check bspwm_backnforth && bspwm_backnforth
    _Check bspwm_external_rules && \
        bspc config external_rules_command \
            "$(which bspwm_external_rules)"

    #### BSPC CONFIG CALLS ####

    declare -a settings=(
        "automatic_scheme spiral" \
        "border_width 1" \
        "borderless_monocle true" \
        "bottom_padding 0" \
        "click_to_focus button1" \
        "center_pseudo_tiled true" \
        "focus_follows_pointer true" \
        "gapless_monocle true" \
        "ignore_ewmh_focus true" \
        "initial_polarity first_child" \
        "left_padding 0" \
        "pointer_modifier control" \
        "pointer_follows_monitor true" \
        "pointer_follows_focus true" \
        "pointer_action1 move" \
        "pointer_action2 resize_side" \
        "pointer_action3 resize_corner" \
        "presel_feedback true" \
        "right_padding 0" \
        "single_monocle true" \
        "split_ratio 0.52" \
        "top_padding 24" \
        "window_gap 5"
    )

    for opts in "${settings[@]}"; do
        # we want term splitting, so we don't quote here.
        # shellcheck disable=SC2086
        set -- $opts
        bspc config "$@"
    done

    #### BSPC CONFIG COLORS (see _GetColors function) ####
    # RESOURCES_FILE is an environment variable

    [[ -f $RESOURCES_FILE ]] && _GetColors

    #### BSPWM SPECIFIC CURSOR SHAPE ####

    xsetroot -cursor_name left_ptr

    _WindowRules

}

_Check() { command -v "$1" >/dev/null; }

_GetColors() {

    local red cyn mag bkg

    red=$(xrdb -query | awk '/color1:/{print $NF}')
    cyn=$(xrdb -query | awk '/color6:/{print $NF}')
    mag=$(xrdb -query | awk '/color5:/{print $NF}')
    bkg=$(xrdb -query | awk '/background:/{print $NF}')

    bspc config active_border_color   "$bkg"
    bspc config focused_border_color  "$cyn"
    bspc config normal_border_color   "$mag"
    bspc config presel_feedback_color "$red"

}

_Rules() { bspc rule -a "$@"; }

case "$1" in
    -r) source ~/.config/bspwm/_WindowRules
        _WindowRules
        _GetColors
        notify-send 'window rules reloaded'
        exit 0
    ;;
esac

_Main "${@}"
